# Generated by Django 3.0 on 2019-12-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Run_from',
            new_name='Runs_from',
        ),
    ]
